# **Exercise 1**

In [ ]:
# 1.1 Import numpy and transform the following list into a NumPy array
a = [10,39,10,20,40,21,55,23,66,76]


In [ ]:
# 1.2 Select all values larger than 20 with boolean indexing


array([39, 40, 21, 55, 23, 66, 76])

In [ ]:
# 1.3 Add the following list of values to a
b = [2,4,5]


[10 39 10 20 40 21 55 23 66 76  2  4  5]


In [ ]:
# 1.4 compute mean and standard deviation of this array


mean 28.53846153846154
std 23.705291147808474


In [ ]:
# 1.5  multiply each value in list a by 2


array([ 9, 38,  9, 19, 39, 20, 54, 22, 65, 75,  1,  3,  4])

# **Exercise 2**

In [ ]:
data = {
        "Name":["Clara", "Tom", "Sarah", "John"],
        "Gender":["F","M","F","M"],
        "Age":[20,25,28,22]
        }

In [ ]:
# 2.1 import pandas and create a dataframe from dictionary data
import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("")
sns.pairplot(iris, hue="")
plt.show()

In [ ]:
# 2.2 Add a new column 'Grade' with the list grades to the dataframe
grades = [2,3,4,1]

In [ ]:
# 2.3 sort the entries of the dataframe by their age


In [ ]:
# 2.4 compute the mean age


In [ ]:
# 2.5 compute the mean age of all female persons


# **Exercise 3**

In [ ]:
data = {
        "Name":["Clara", "Tom", "Sarah"],
        "Gender":["F","M","F"],
        "Age":[20,25,28]
        }


data2 = {
        "Name":["Clara", "Tom", "John"],
        "Subject":["Physics","Politics","English"],
        "Grade":[2,1,3]
        }
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data2)

In [ ]:
# 3.1 merge df1 and df2 on Name, try out left, right joins


In [ ]:
# 3.2 Compute the mean age per gender for df1 with a group-by


## **Exercise 4**

In [21]:
# Execute this cell to import pandas and load data
import pandas as pd
df = pd.read_csv('https://drive.google.com/uc?id=1Rzq2VqPVRM2kfMuh_jToJKzKUvBOC0vp')

# some cleaning, we come to this topic later
df['price'] = df['price'].str.replace('$','').str.replace(',','').astype(float)
df

id  price neighbourhood_group_cleansed   latitude  longitude  \
0      28684898   50.0                     Neukölln  52.473978  13.454423   
1      22607348   10.0           Treptow - Köpenick  52.468095  13.487103   
2      21019199   35.0                     Neukölln  52.481810  13.437268   
3      21919556   99.0                       Pankow  52.537269  13.416036   
4       4820648   39.0     Friedrichshain-Kreuzberg  52.491483  13.387362   
...         ...    ...                          ...        ...        ...   
13526  17783594   38.0           Treptow - Köpenick  52.469634  13.588212   
13527  28732723   45.0                       Pankow  52.548687  13.448582   
13528   7823323   22.0                        Mitte  52.524995  13.336786   
13529    901569   40.0                       Pankow  52.530876  13.433975   
13530  21608963   45.0                     Neukölln  52.481689  13.431743   

       bathrooms  availability_30  beds  bedrooms  review_scores_value  \
0            1.0               18   2.0       2.0                  9.0   
1            1.0                0   1.0       1.0                  9.0   
2            1.0                0   1.0       1.0                  9.0   
3            2.0                0   2.0       2.0                  NaN   
4            1.0                0   1.0       1.0                  9.0   
...          ...              ...   ...       ...                  ...   
13526        1.0               18   2.0       2.0                  9.0   
13527        1.0                0   1.0       1.0                  NaN   
13528        2.0                0   1.0       1.0                  9.0   
13529        1.0                5   1.0       1.0                 10.0   
13530        1.0               16   1.0       1.0                  8.0   

       bed_type  minimum_nights  maximum_nights  availability_365  \
0      Real Bed               1              13                73   
1      Real Bed              30            1124               156   
2      Real Bed               1            1125                 0   
3      Real Bed              14              41                35   
4      Real Bed              60            1125               289   
...         ...             ...             ...               ...   
13526  Real Bed               1              14                65   
13527  Real Bed               6              14                 0   
13528  Real Bed               4              12                 0   
13529  Real Bed               2              45               334   
13530  Real Bed               3              60                19   

      property_type is_business_travel_ready cleaning_fee        room_type  \
0         Apartment                        f        $0.00     Private room   
1         Apartment                        f          NaN     Private room   
2         Apartment                        f       $15.00     Private room   
3         Apartment                        f       $50.00  Entire home/apt   
4         Apartment                        f          NaN  Entire home/apt   
...             ...                      ...          ...              ...   
13526     Apartment                        f       $50.00  Entire home/apt   
13527     Apartment                        f        $0.00  Entire home/apt   
13528     Apartment                        f          NaN     Private room   
13529     Apartment                        f          NaN     Private room   
13530     Apartment                        f       $15.00  Entire home/apt   

       square_feet  guests_included  
0              NaN                1  
1              NaN                1  
2              NaN                1  
3              NaN                1  
4              NaN                1  
...            ...              ...  
13526          NaN                1  
13527          NaN                1  
13528          NaN                1  
13529          0.0                1  
13530          

In [25]:
df.neighbourhood_group_cleansed.value_counts()



neighbourhood_group_cleansed
Friedrichshain-Kreuzberg    3263
Mitte                       2767
Pankow                      2165
Neukölln                    2094
Charlottenburg-Wilm.         958
Tempelhof - Schöneberg       930
Lichtenberg                  403
Treptow - Köpenick           372
Steglitz - Zehlendorf        261
Reinickendorf                149
Marzahn - Hellersdorf         93
Spandau                       76
Name: count, dtype: int64

In [73]:
numbers = df.neighbourhood_group_cleansed.value_counts()
Number2 = df.neighbourhood_group_cleansed.valuse_count('price')

numbers * avp


AttributeError: 'Series' object has no attribute 'valuse_count'

In [74]:
display(avp * numbers)

neighbourhood_group_cleansed
Charlottenburg-Wilm.        128093.0
Friedrichshain-Kreuzberg    203060.0
Lichtenberg                  25652.0
Marzahn - Hellersdorf         5469.0
Mitte                       193496.0
Neukölln                     98354.0
Pankow                      151359.0
Reinickendorf                 7601.0
Spandau                       4289.0
Steglitz - Zehlendorf        14317.0
Tempelhof - Schöneberg       97472.0
Treptow - Köpenick           19126.0
dtype: float64